# remoteConfiguration.enabled -- If true, enables Remote Configuration in the Datadog Operator (beta). Requires clusterName, API and App keys to be set.

remoteConfiguration:
  enabled: true

apiKeyExistingSecret: datadog-operator-secret
appKeyExistingSecret: datadog-operator-secret

podLabels:
  tags.datadoghq.com/service: datadog-operator
